# Base configuration for book recommendation API

# Server configuration
host = "0.0.0.0"
port = "${APP_PORT}"
environment = "development"
frontend_url = "http://localhost:3000"

# Database configuration
database_url = "postgres://localhost:5432/books"


# Pinecone configuration
pinecone_api_key = "${APP_PINECONE_API_KEY}"
pinecone_environment = "${APP_PINECONE_ENV}"
pinecone_index = "${APP_PINECONE_INDEX_NAME}"

# HuggingFace configuration
huggingface_api_key = "${APP_HUGGINGFACE_API_KEY}"

# Neo4j configuration
neo4j_uri = "${APP_NEO4J_URI}"
neo4j_user = "${APP_NEO4J_USER}"
neo4j_password = "${APP_NEO4J_PASSWORD}"

# Logging configuration
log_level = "info"
